# SSH KEY (Generated by Terraform)
name = "vm-nic"
location = azurerm_resource_group.rg.location
resource_group_name = azurerm_resource_group.rg.name


ip_configuration {
name = "internal"
subnet_id = azurerm_subnet.subnet.id
private_ip_address_allocation = "Dynamic"
public_ip_address_id = azurerm_public_ip.pip.id
}
}


# -----------------------------
# LINUX VM (.NET READY)
# -----------------------------
resource "azurerm_linux_virtual_machine" "vm" {
name = "dotnet-vm"
resource_group_name = azurerm_resource_group.rg.name
location = azurerm_resource_group.rg.location
size = "Standard_B2s"
admin_username = var.admin_username


network_interface_ids = [azurerm_network_interface.nic.id]


admin_ssh_key {
username = var.admin_username
public_key = tls_private_key.vm_key.public_key_openssh
}


os_disk {
caching = "ReadWrite"
storage_account_type = "Standard_LRS"
}


source_image_reference {
publisher = "Canonical"
offer = "0001-com-ubuntu-server-jammy"
sku = "22_04-lts"
version = "latest"
}


custom_data = base64encode(<<EOF
#!/bin/bash
apt-get update -y
apt-get install -y aspnetcore-runtime-8.0
mkdir -p /var/www/app
chown ${var.admin_username}:${var.admin_username} /var/www/app
EOF
)
}
